[package]
name = "math"
version = "1.0.0"
description = "Motoko linear algebra and mathematical calculus module"
repository = "https://github.com/ArielRobotti/math"
keywords = [
  "Motoko",
  "Math",
  "Matrix",
  "Algebra",
  "linealAlgebra",
  "dotProduct",
  "determinant"
]
license = "MIT"

[dependencies]
base = "0.11.0"
